exec:
  default:
    - when: ExitCode != 0
      template: |
        ## {{template "link" .}}

        {{template "status" .}}
        {{template "join_command" .}}
        {{template "hidden_combined_output" .}}
