name: split-and-push

on:
  push:
    branches:
      - main

jobs:
  prepare-repositories:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: github-repositories
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: v1.0.3
          terraform_wrapper: false
      - id: akoi
        uses: int128/akoi-action@main
      - uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SERVIEC_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Run terraform apply
        run: |
          github-comment exec -- terraform init -input=false
          tfcmt plan -- terraform plan -input=false -out tfplan.binary
          tfcmt apply -- terraform apply -input=false tfplan.binary
        env:
          GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}

  split-and-push:
    runs-on: ubuntu-latest
    needs: prepare-repositories
    strategy:
      matrix:
        module: [foo, bar]
    steps:
      - uses: actions/checkout@v2
      - name: Split subtree and push to poly repo
        run: |
          git subtree split --prefix=modules/${{ matrix.module }} -b git-subtree-split
          git checkout git-subtree-split
          git remote add subtree-repo https://github.com/yuya-takeyama/terraform-module-${{ matrix.module }}.git
          git push -f subtree-repo git-subtree-split:main
