name: test

on:
  pull_request:

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: github-repositories
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: v1.0.3
          terraform_wrapper: false
      - id: akoi
        uses: int128/akoi-action@v2
      - uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SERVIEC_ACCOUNT_KEY }}
          export_default_credentials: true
      - name: Run terraform plan
        run: |
          github-comment hide
          github-comment exec -- terraform init -input=false
          tfcmt plan -- terraform plan -input=false -out tfplan.binary
        env:
          GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
